#!/bin/bash
# Start HBase
#  1) hbase master (which runs the local region server)

sed -i 's/HOSTNAME/'"$HOSTNAME"'/' /opt/hbase/conf/hbase-site.xml
sed -i 's/HOSTNAME/'"$HOSTNAME"'/' /opt/hbase/conf/zoo.cfg
sed -i 's/localhost/'"$HOSTNAME"'/' /opt/hbase/conf/regionservers
sed -i s/NAMENODE_PORT/$NAMENODE_PORT/ /opt/hbase/conf/hbase-site.xml

logs_dir=/data/logs

mkdir -p $logs_dir /data/hbase /data/run

# Master server (Foreground) that also starts the region server
# Ports: Master: 16000 API, 16010 UI; 2181 ZK;  Region: 16020 API, 16030 UI
echo "hbase master start logging to $logs_dir/hbase-master.log"
exec hbase master start 2>&1 | tee $logs_dir/hbase-master.log
