#!/bin/bash
# Start HBase

logs_dir=/data/logs

mkdir -p $logs_dir /data/hbase /data/run

# Master server (Foreground) that also starts the region server
# Ports: Master: 16000 API, 16010 UI; 2181 ZK;  Region: 16020 API, 16030 UI
echo "hbase master start logging to $logs_dir/hbase-master.log"
exec /opt/hbase/bin/hbase master start 2>&1 | tee $logs_dir/hbase-master.log
